apiVersion: v1
kind: Service
metadata:
  name: mosquitto-lb
  namespace: tpi-mosquitto
  labels:
    app: mosquitto
    tier: frontend
spec:
  selector:
    app: mosquitto
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
  - name: http
    port: 9001
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-claim
  namespace: tpi-mosquitto
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: tpi-mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
        tier: frontend
    spec:
      containers:
      - name: mosquitto
        image: arm64v8/eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: http
        volumeMounts:
        - name: mosquitto-persistent-storage
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password.txt
          subPath: password.txt
      volumes:
      - name: mosquitto-persistent-storage
        persistentVolumeClaim:
          claimName: mosquitto-data-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
