apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: tpi-mosquitto
  labels:
    app: mosquitto
data:
  password.txt: |
    admin:$7$101$tz6arXoVTIHSiOis$msNpyhYVntBTDtPjHeUhr8YAckwsKfQRivH9hm+It7Bn3/1OB2aBHQq+S0n5AZMokqRtv79Rzh5oZMwnnhtXZw==
    tpimqtt:$7$101$m00uFi/ktdReQvkf$E3VSPpR+CCsTdjsqXiPASlrhY883MEw6tvjK0MIG2c4ceBdBu2dKwVE1GVna1Ac60x7sT6CYGc00pkc24XnlAw==
