apiVersion: v1
kind: Namespace
metadata:
  name: tpi-grafana

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tpi-grafana
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: grafana
  type: LoadBalancer # Or ClusterIP for internal access

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tpi-grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest # Replace with your desired version
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
  namespace: tpi-grafana
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 100Mi # Adjust storage size as needed
